export const ActionTypes = {
    ADD_PLAN: "ADD_PLAN",
    SET_PLANS: "SET_PLANS",
    SAVE_PLAN: "SAVE_PLAN",
    DELETE_PLAN: "DELETE_PLAN",
    SELECTED_PLAN: "SELECTED_PLAN",
    SET_DAILY_PLAN: "SET_DAILY_PLAN",
    SET_WEEKLY_PLAN: "SET_WEEKLY_PLAN",
    SET_YEARLY_PLAN: "SET_YEARLY_PLAN",
    REMOVE_SAVE_PLAN: "REMOVE_SAVE_PLAN",
    SET_MONTHLY_PLAN: "SET_MONTHLY_PLAN",
    SELECTED_CATEGORY: "SELECTED_CATEGORY",
}